const frases = [
  "¡Cree en ti y todo será posible!",
  "El único límite es el que tú mismo te pones.",
  "La disciplina es el puente entre metas y logros.",
  "No importa cuántas veces caigas, sino cuántas te levantes.",
  "Hoy es un buen día para empezar algo grandioso.",
  "Cada paso que das te acerca a donde quieres estar.",
  "No llores porque ya se terminó, sonríe porque sucedió.",
  "Podrán cortar todas las flores, pero no podrán detener la primavera.",
  "La perfección es una pulida colección de errores.",
  "Uno está enamorado cuando se da cuenta de que otra persona es única.",
  "Nada está perdido si se tiene el valor de proclamar que todo está perdido y hay que empezar de nuevo.",
  "Escribir es un acto de fe, no un truco de gramática.",
  "Caminante, no hay camino, se hace camino al andar.",
  "El amor es una fuerza, más formidable que cualquier otra.",
  "El alma tiene ilusiones, como el pájaro alas. Eso es lo que la sostiene.",
  "Cada libro, cada tomo que ves, tiene alma.",
  "La poesía no quiere adeptos, quiere amantes.",
  "El que lee mucho y anda mucho, ve mucho y sabe mucho.",
  "No estudio por saber más, sino por ignorar menos.",
  "El verdadero arte de la memoria es el arte de la atención.",
  "Nada comienza, nada termina, todo continúa.",
  "La vida es tan corta y el oficio de vivir tan difícil, que cuando uno empieza a aprenderlo ya hay que morirse.",
  "Somos lo que hacemos para cambiar lo que somos.",
  "Dentro de nosotros existe algo que no tiene nombre, eso es lo que somos.",
  "Las cosas no se piensan porque sean importantes, sino que son importantes porque se piensan.",
  "La libertad es poco, lo que deseo todavía no tiene nombre.",
  "No te rindas, aún estás a tiempo de alcanzar y comenzar de nuevo.",
  "La vida no es la que uno vivió, sino la que uno recuerda y cómo la recuerda para contarla.",
  "Cuando quieres algo, todo el universo conspira para que realices tu deseo.",
  "Son nuestras elecciones, más que nuestras habilidades, las que muestran lo que realmente somos.",
  "Cuando salgas de la tormenta, no serás la misma persona que entró en ella.",
  "Lo que quiero es imposible, lo que quiero es inalcanzable, lo que quiero está en el otro extremo del universo.",
  "Pies para qué los quiero si tengo alas para volar.",
  "En medio del invierno descubrí que había dentro de mí un verano invencible.",
  "El hecho de que te preocupe ser mejor persona ya te convierte en mejor persona.",
  "No hay barrera, cerradura ni cerrojo que puedas imponer a la libertad de mi mente.",
  "Escribir es una forma de amor, es crear vida con palabras.",
  "No somos lo que decimos, somos lo que hacemos.",
  "La verdadera patria del hombre es la infancia.",
  "Sé tú mismo, el resto de los papeles ya están ocupados.",
  "La vida es una aventura atrevida o no es nada en absoluto.",
  "La creatividad requiere valor.",
  "La vida se encoge o se expande en proporción al coraje de uno.",
  "El coraje es gracia bajo presión.",
  "Vivir no es suficiente, uno debe tener sol, libertad y una pequeña flor.",
  "La esperanza es el sueño de los que están despiertos.",
  "Haz de tu vida un sueño, y de tu sueño una realidad.",
  "El futuro pertenece a quienes creen en la belleza de sus sueños.",
  "La felicidad es interior, no exterior; por lo tanto, no depende de lo que tenemos, sino de lo que somos.",
  "Solo se vive una vez, pero si lo haces bien, una vez es suficiente.",
  "No puedes depender de tus ojos cuando tu imaginación está fuera de foco.",
  "Un viaje de mil millas comienza con un solo paso.",
  "Todo lo que puedas imaginar es real.",
  "El primer paso no te lleva a donde quieres ir, pero te saca de donde estás.",
  "No hay nada imposible, porque los sueños de ayer son las esperanzas de hoy y pueden convertirse en realidad mañana."
];

function mostrarFrase() {
  const fraseAleatoria = frases[Math.floor(Math.random() * frases.length)];
  document.getElementById("frase").textContent = fraseAleatoria;
}